### ISSUE TITLE
make Error

### ISSUE THREAD

**Issue by avanisho** [areaDetector/aravisGigE#26]
HI I am trying to make aravisGigE-master but am getting following errors

make -C ./configure install 
make[1]: Entering directory '/home/avanish/Desktop/epics_prog/aravisGigE-master/configure'
make -C O.linux-x86 -f ../Makefile TOP=../.. \
    T_A=linux-x86 install
make[2]: Entering directory '/home/avanish/Desktop/epics_prog/aravisGigE-master/configure/O.linux-x86'
perl -CSD /opt/epics/base/bin/linux-x86/convertRelease.pl checkRelease
make[2]: Leaving directory '/home/avanish/Desktop/epics_prog/aravisGigE-master/configure/O.linux-x86'
make[1]: Leaving directory '/home/avanish/Desktop/epics_prog/aravisGigE-master/configure'
make -C ./vendor install 
make[1]: Entering directory '/home/avanish/Desktop/epics_prog/aravisGigE-master/vendor'
make -C O.linux-x86 -f ../Makefile TOP=../.. \
    T_A=linux-x86 install
make[2]: Entering directory '/home/avanish/Desktop/epics_prog/aravisGigE-master/vendor/O.linux-x86'
make[2]: Nothing to be done for 'install'.
make[2]: Leaving directory '/home/avanish/Desktop/epics_prog/aravisGigE-master/vendor/O.linux-x86'
make[1]: Leaving directory '/home/avanish/Desktop/epics_prog/aravisGigE-master/vendor'
make -C ./aravisGigEApp install 
make[1]: Entering directory '/home/avanish/Desktop/epics_prog/aravisGigE-master/aravisGigEApp'
make -C ./src install 
make[2]: Entering directory '/home/avanish/Desktop/epics_prog/aravisGigE-master/aravisGigEApp/src'
make -C O.linux-x86 -f ../Makefile TOP=../../.. \
    T_A=linux-x86 install
make[3]: Entering directory '/home/avanish/Desktop/epics_prog/aravisGigE-master/aravisGigEApp/src/O.linux-x86'
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE            -D_X86_  -DUNIX  -Dlinux     -O3 -g   -Wall      -mtune=generic     -m32 -D_FILE_OFFSET_BITS=64 -fPIC -I. -I../O.Common -I. -I. -I.. -I/opt/epics/base-3.15.3/include/compiler/gcc -I/opt/epics/base-3.15.3/include/os/Linux -I/opt/epics/base-3.15.3/include      -I -I -I../../../vendor/aravis-linux-x86/include/aravis-0.4    -c ../aravisCamera.cpp
../aravisCamera.cpp: In function ‘void newBufferCallback(ArvStream_, aravisCamera_)’:
../aravisCamera.cpp:192:38: error: invalid conversion from ‘long unsigned int_’ to ‘size_t_ {aka unsigned int_}’ [-fpermissive]
     arv_buffer_get_data(buffer, &size);
                                      ^
In file included from /opt/epics/base-3.15.3/include/arv.h:64:0,
                 from ../aravisCamera.cpp:31:
/opt/epics/base-3.15.3/include/arvbuffer.h:118:15: note:   initializing argument 2 of ‘const void_ arv_buffer_get_data(ArvBuffer_, size_t_)’
 const void \*  arv_buffer_get_data  (ArvBuffer _buffer, size_t *size);
               ^
../aravisCamera.cpp: In constructor ‘aravisCamera::aravisCamera(const char_, const char_, int, size_t, int, int)’:
../aravisCamera.cpp:256:5: warning: ‘void g_thread_init(gpointer)’ is deprecated [-Wdeprecated-declarations]
     g_thread_init (NULL);
     ^
In file included from /opt/epics/base-3.15.3/include/glib.h:107:0,
                 from /opt/epics/base-3.15.3/include/gobject/gbinding.h:28,
                 from /opt/epics/base-3.15.3/include/glib-object.h:23,
                 from /opt/epics/base-3.15.3/include/arvenums.h:26,
                 from /opt/epics/base-3.15.3/include/arvtypes.h:26,
                 from /opt/epics/base-3.15.3/include/arv.h:26,
                 from ../aravisCamera.cpp:31:
/opt/epics/base-3.15.3/include/glib/deprecated/gthread.h:265:10: note: declared here
 void     g_thread_init                   (gpointer vtable);
          ^
../aravisCamera.cpp:256:5: warning: ‘void g_thread_init(gpointer)’ is deprecated [-Wdeprecated-declarations]
     g_thread_init (NULL);
     ^
In file included from /opt/epics/base-3.15.3/include/glib.h:107:0,
                 from /opt/epics/base-3.15.3/include/gobject/gbinding.h:28,
                 from /opt/epics/base-3.15.3/include/glib-object.h:23,
                 from /opt/epics/base-3.15.3/include/arvenums.h:26,
                 from /opt/epics/base-3.15.3/include/arvtypes.h:26,
                 from /opt/epics/base-3.15.3/include/arv.h:26,
                 from ../aravisCamera.cpp:31:
/opt/epics/base-3.15.3/include/glib/deprecated/gthread.h:265:10: note: declared here
 void     g_thread_init                   (gpointer vtable);
          ^
../aravisCamera.cpp:256:24: warning: ‘void g_thread_init(gpointer)’ is deprecated [-Wdeprecated-declarations]
     g_thread_init (NULL);
                        ^
In file included from /opt/epics/base-3.15.3/include/glib.h:107:0,
                 from /opt/epics/base-3.15.3/include/gobject/gbinding.h:28,
                 from /opt/epics/base-3.15.3/include/glib-object.h:23,
                 from /opt/epics/base-3.15.3/include/arvenums.h:26,
                 from /opt/epics/base-3.15.3/include/arvtypes.h:26,
                 from /opt/epics/base-3.15.3/include/arv.h:26,
                 from ../aravisCamera.cpp:31:
/opt/epics/base-3.15.3/include/glib/deprecated/gthread.h:265:10: note: declared here
 void     g_thread_init                   (gpointer vtable);
          ^
../aravisCamera.cpp:257:5: warning: ‘void g_type_init()’ is deprecated [-Wdeprecated-declarations]
     g_type_init ();
     ^
In file included from /opt/epics/base-3.15.3/include/gobject/gobject.h:24:0,
                 from /opt/epics/base-3.15.3/include/gobject/gbinding.h:29,
                 from /opt/epics/base-3.15.3/include/glib-object.h:23,
                 from /opt/epics/base-3.15.3/include/arvenums.h:26,
                 from /opt/epics/base-3.15.3/include/arvtypes.h:26,
                 from /opt/epics/base-3.15.3/include/arv.h:26,
                 from ../aravisCamera.cpp:31:
/opt/epics/base-3.15.3/include/gobject/gtype.h:681:23: note: declared here
 void                  g_type_init                    (void);
                       ^
../aravisCamera.cpp:257:5: warning: ‘void g_type_init()’ is deprecated [-Wdeprecated-declarations]
     g_type_init ();
     ^
In file included from /opt/epics/base-3.15.3/include/gobject/gobject.h:24:0,
                 from /opt/epics/base-3.15.3/include/gobject/gbinding.h:29,
                 from /opt/epics/base-3.15.3/include/glib-object.h:23,
                 from /opt/epics/base-3.15.3/include/arvenums.h:26,
                 from /opt/epics/base-3.15.3/include/arvtypes.h:26,
                 from /opt/epics/base-3.15.3/include/arv.h:26,
                 from ../aravisCamera.cpp:31:
/opt/epics/base-3.15.3/include/gobject/gtype.h:681:23: note: declared here
 void                  g_type_init                    (void);
                       ^
../aravisCamera.cpp:257:18: warning: ‘void g_type_init()’ is deprecated [-Wdeprecated-declarations]
     g_type_init ();
                  ^
In file included from /opt/epics/base-3.15.3/include/gobject/gobject.h:24:0,
                 from /opt/epics/base-3.15.3/include/gobject/gbinding.h:29,
                 from /opt/epics/base-3.15.3/include/glib-object.h:23,
                 from /opt/epics/base-3.15.3/include/arvenums.h:26,
                 from /opt/epics/base-3.15.3/include/arvtypes.h:26,
                 from /opt/epics/base-3.15.3/include/arv.h:26,
                 from ../aravisCamera.cpp:31:
/opt/epics/base-3.15.3/include/gobject/gtype.h:681:23: note: declared here
 void                  g_type_init                    (void);
                       ^
/opt/epics/base/configure/RULES_BUILD:228: recipe for target 'aravisCamera.o' failed
make[3]: *_\* [aravisCamera.o] Error 1
make[3]: Leaving directory '/home/avanish/Desktop/epics_prog/aravisGigE-master/aravisGigEApp/src/O.linux-x86'
/opt/epics/base/configure/RULES_ARCHS:61: recipe for target 'install.linux-x86' failed
make[2]: **\* [install.linux-x86] Error 2
make[2]: Leaving directory '/home/avanish/Desktop/epics_prog/aravisGigE-master/aravisGigEApp/src'
/opt/epics/base/configure/RULES_DIRS:88: recipe for target 'src.install' failed
make[1]: **\* [src.install] Error 2
make[1]: Leaving directory '/home/avanish/Desktop/epics_prog/aravisGigE-master/aravisGigEApp'
/opt/epics/base/configure/RULES_DIRS:88: recipe for target 'aravisGigEApp.install' failed
make: **\* [aravisGigEApp.install] Error 2
avanish@avanish-dell:~/Desktop/epics_prog/aravisGigE-master$ 

Please suggest how to make
I am having ubuntu-32bits and processor is 64 bit.

**Comment by MarkRivers** [comment]
Something looks strange here:

    make[3]: Entering directory '/home/avanish/Desktop/epics_prog/aravisGigE-master/aravisGigEApp/src/O.linux-x86'
    /usr/bin/g++ -D_GNU_SOURCE -D_DEFAULT_SOURCE -D_X86_ -DUNIX -Dlinux -O3 -g -Wall -mtune=generic -m32 -D_FILE_OFFSET_BITS=64 -fPIC -I. -I../O.Common -I. -I. -I.. -I/opt/epics/base-3.15.3/include/compiler/gcc -I/opt/epics/base-3.15.3/include/os/Linux -I/opt/epics/base-3.15.3/include -I -I -I../../../vendor/aravis-linux-x86/include/aravis-0.4 -c ../aravisCamera.cpp
    ../aravisCamera.cpp: In function ‘void newBufferCallback(ArvStream, aravisCamera)’:
    ../aravisCamera.cpp:192:38: error: invalid conversion from ‘long unsigned int’ to ‘size_t {aka unsigned int}’ [-fpermissive]
    arv_buffer_get_data(buffer, &size);

    In file included from /opt/epics/base-3.15.3/include/arv.h:64:0,
    from ../aravisCamera.cpp:31:
    /opt/epics/base-3.15.3/include/arvbuffer.h:118:15: note: initializing argument 2 of ‘const void arv_buffer_get_data(ArvBuffer, size_t)’

It says it is getting arv.h from /opt/epics/base-3.15.3/include.  Where did you install the aravis vendor library?  The aravisGigE module is set up to install it in aravisGigE/vendor/ directory.  On my system the include files get installed here:
    /areaDetector/aravisGigE/vendor/aravis-linux-x86_64/include/aravis-0.4

However, it does appear that the aravisGigE may not build on 32-bit Linux systems, because vendor/Makefile contains the lines:

    BIN_INSTALLS_Linux  += $(addprefix ../aravis-linux-x86_64/bin/, $(ARAVIS_LINUX_BINS))
    LIB_INSTALLS_Linux  += $(addprefix ../aravis-linux-x86_64/lib/, $(ARAVIS_LINUX_LIBS))
    ARAVISMAK = $(TOP)/vendor/aravis-linux-x86_64/Makefile

There does seem to be an error in aravisCamera.cpp because the final argument to arv_buffer_get_data is defined as size_t in arvbuffer.h, but as unsigned long in aravisCamera.cpp.  However, on both 32-bit and 64-bit Linux this is normally OK because size_t and unsigned long are both the same size (e.g. both 32 or both 64 bits) on Linux?

**Comment by avanisho** [comment]
Thank you for your answer.
I have installed my aravisGigE module under /Desktop/epics_prog/aravisGigE/vendor.
Include file arv.h is also installed under /vendor/aravis-linux-x86_64/include/aravis-0.4.
But when I am trying to make it was giving following error

make -C ./configure install 
make[1]: Entering directory '/home/avanish/Desktop/epics_prog/aravisGigE/configure'
make -C O.linux-x86 -f ../Makefile TOP=../.. \
    T_A=linux-x86 install
make[2]: Entering directory '/home/avanish/Desktop/epics_prog/aravisGigE/configure/O.linux-x86'
perl -CSD /opt/epics/base/bin/linux-x86/convertRelease.pl checkRelease
make[2]: Leaving directory '/home/avanish/Desktop/epics_prog/aravisGigE/configure/O.linux-x86'
make[1]: Leaving directory '/home/avanish/Desktop/epics_prog/aravisGigE/configure'
make -C ./vendor install 
make[1]: Entering directory '/home/avanish/Desktop/epics_prog/aravisGigE/vendor'
make -C O.linux-x86 -f ../Makefile TOP=../.. \
    T_A=linux-x86 install
make[2]: Entering directory '/home/avanish/Desktop/epics_prog/aravisGigE/vendor/O.linux-x86'
make[2]: Nothing to be done for 'install'.
make[2]: Leaving directory '/home/avanish/Desktop/epics_prog/aravisGigE/vendor/O.linux-x86'
make[1]: Leaving directory '/home/avanish/Desktop/epics_prog/aravisGigE/vendor'
make -C ./aravisGigEApp install 
make[1]: Entering directory '/home/avanish/Desktop/epics_prog/aravisGigE/aravisGigEApp'
make -C ./src install 
make[2]: Entering directory '/home/avanish/Desktop/epics_prog/aravisGigE/aravisGigEApp/src'
make -C O.linux-x86 -f ../Makefile TOP=../../.. \
    T_A=linux-x86 install
make[3]: Entering directory '/home/avanish/Desktop/epics_prog/aravisGigE/aravisGigEApp/src/O.linux-x86'
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE            -D_X86_  -DUNIX  -Dlinux     -O3 -g   -Wall      -mtune=generic     -m32 -D_FILE_OFFSET_BITS=64 -fPIC -I. -I../O.Common -I. -I. -I.. -I/opt/epics/base-3.15.3/include/compiler/gcc -I/opt/epics/base-3.15.3/include/os/Linux -I/opt/epics/base-3.15.3/include      -I -I -I../../../vendor/aravis-linux-x86/include/aravis-0.4    -c ../aravisCamera.cpp
../aravisCamera.cpp:31:21: fatal error: arv.h: No such file or directory
compilation terminated.

SO I make a symbolic link of arv.h in directory /opt/epics/base-3.15.3/include and all other header files which were giving errors during make.

Please suggest how to install aravis module.

**Comment by bhill-slac** [comment]
Hi avanisho,
As you appear to be running a 32bit linux, I think the first thing you 
should
try is to change all the linux-x86_64 references in TOP/vendor/Makefile 
to linux-x86,
then run make again.    You may need to fix some 32bit vs 64bit build 
errors such
as the size_t vs unsigned long error that Mark mentioned in his reply.   
I'm not
sure how many errors you'll find as we run 64bit.

Check afterward to make sure it built the following libs and executable:
TOP/vendor/aravis-linux-x86/lib/linux-x86/libaravis-0.4.a
TOP/vendor/aravis-linux-x86/lib/linux-x86/libaravis-0.4.so
TOP/vendor/aravis-linux-x86/bin/linux-x86/arv-tool-0.4
TOP/vendor/aravis-linux-x86/include/arv.h

If you don't see those, cd to TOP/vendor/aravis-linux-x86 and run make
there, fixing any errors till the files above are built.   You won't 
need the symbolic
link to arv.h once that works.  You also don't need to install the 
module to use it.
Once everything has built successfully you'll have a sample ioc 
executable here:
TOP/bin/linux-x86/aravisGigEApp

Another alternative since you said you had a 64bit cpu would be to 
switch from 32bit linux
to 64bit linux as I think most of the aravisGigE users are on 64bit linux.

Regards,
- Bruce

**Comment by bhill-slac** [comment]
Oops, wrong include path.  Should be:
TOP/vendor/aravis-linux-x86/include/aravis-0.4/arv.h

**Comment by MarkRivers** [comment]
I am closing this issue since there were suggestions on how to fix the problem and no followup for 2 years.
