### ISSUE TITLE
AravisGigE R2-2

### ISSUE THREAD

**Issue by hhslepicka** [areaDetector/aravisGigE#36]
Hi,

I was wondering if a new release of the aravisGigE module could be cut to include all the new features added since the last version that is almost 1 year old. 🎂 

Thank you!

**Comment by ulrikpedersen** [comment]
I agree that we should roll another release. The way that I would like to see this done is as follows:

* Update AravisGigE to work with the latest areaDetector 2 release (i.e. 2.6)
* Release the current state of master against ADCore 2.6
* Merge #35
  * This is a major rework and requires a careful review and some tweaks to work in our environment
* Do a new release against ADCore 2.6
* Update and roll another release for ADCore 3.0

Unfortunately @thomascobb is rather busy on a number of other projects for the next several months. I'm trying to find someone else to take it on but I'd welcome contributions in Pull Requests and any reports from testing with later ADCore versions.

**Comment by MarkRivers** [comment]
I don't think you need the final step for ADCore R3-0 above.  Nothing needs to change in this driver between R2-6 and R3-0.  Plugins need minor changes but drivers do not.

**Comment by ulrikpedersen** [comment]
OK, thanks, that helps.

**Comment by MarkRivers** [comment]
Any chance of creating a new R2-2 tag and updating the RELEASE.md file?

**Comment by hinxx** [comment]
I'm working with several cameras that use aravisGigE and can run 'master' on the way to R2-2 right away. It will not be a 'careful review' but more along the 'see if it works' lines..

**Comment by ulrikpedersen** [comment]
> It will not be a 'careful review' but more along the 'see if it works' lines..

That's a very good start. Please let us know what you find @hinxx 

Thanks!

**Comment by hhslepicka** [comment]
Aravis 3-0 was released.

**Comment by MarkRivers** [comment]
@hhslepicka just to be clear you mean aravisGigE R3-0 was released.  aravis latest release is 0.8.1.

**Comment by hhslepicka** [comment]
@MarkRivers that is correct! I updated my comment.
