### ISSUE TITLE
Using arv_buffer_get_timestamp() for timeStamp

### ISSUE THREAD

**Issue by hinxx** [areaDetector/aravisGigE#37]
Hi,

what is supposed to be expected 'pRaw->timeStamp' value set by this line of code:

pRaw->timeStamp = arv_buffer_get_timestamp(buffer) / 1.e9;

Is it seconds from epoch?

Given the comment on https://aravisproject.github.io/docs/aravis-0.4/ArvBuffer.html about arv_buffer_get_timestamp(), is it safe to rely on it? I do not see any calls to arv_buffer_set_timestamp() to initially set the timestamp.

I'm asking in regard to the HDF5 saving of images and later correlation to other captured data where I would expect timestamps to be comparable.

**Comment by MarkRivers** [comment]
The NDArray class has 2 timestamp fields. These are the comments for those from NDArray.h
```
    double        timeStamp;    /**< The time stamp in seconds for this array; seconds since Epoch (00:00:00 UTC, January 1, 1970)
                                  * is recommended, but some drivers may use a different start time.*/
    epicsTimeStamp epicsTS;     /**< The epicsTimeStamp; this is set with pasynManager->updateTimeStamp(),
                                  * and can come from a user-defined timestamp source. */
```
**epicsTS** will generally be the time from epicsTimeGetCurrent(), and so will use the EPICS epoch which is January 1, 1990.  Many drivers also set **timeStamp** to use the EPICS epoch not the Unix/Linux epoch, which disagrees with the comments in the header. (Perhaps that comment should be changed?)  Some cameras also have their own internal clock values which are sent with the image data (e.g. Prosilica), and those values are generally stored in **timeStamp.**  They may have a completely different epoch, e.g. the time the camera was powered on.

**Comment by thomascobb** [comment]
All our cameras using aravisGigE report the time since power on in arv_buffer_get_timestamp(). I'm not particularly attached to that behaviour, so I'd be happy to see timeStamp to seconds since the Unix/Linux epoch if that makes it more consistent with other drivers.

**Comment by hinxx** [comment]
Thanks @MarkRivers, the 'EPICS epoch' explains it!
IMO, changing the comment to reflect real situation sounds good.

**Comment by MarkRivers** [comment]
I have changed the comment.
