### ISSUE TITLE
Need medm screens for aravis.

### ISSUE THREAD

**Issue by MarkRivers** [areaDetector/aravisGigE#39]
I am planning to make a new Python program makeAdl.py that is based on makeDbAndEdl.py.  It will create medm screens from which I can autogenerate edm, caQtDM, and CSS-BOY screens.

I think the edm auto-generated feature screen is too wide to be useful.  I plan to (eventually) have each category be its own screen (AcquisitionControl, AnalogControl, ImageFormatControl) that will be called up as related displays.  This seems more scaleable as the number of features gets large.

Has anyone else started this?

**Comment by bhill-slac** [comment]
Hi Mark,
I've considered changing makeDbAndEdl.py to generate tab selected related displays for each category, but I'm not sure it would make a more usable screen.   For example, one of our Basler cameras has 45 feature categories,    One category has 35 features, but nearly half have just 2 features so to see them all you'd need to select each different tab.

In practice, I create a custom screen for each camera model with the features I think are most relevant and provide the full features screen for those who want to explore what other features are available.
Cheers, Bruce

**Comment by MarkRivers** [comment]
I now have a working version of makeAdl.py, based on makeDbAndEdl.py.  It is producing a functioning medm display:

![image](https://user-images.githubusercontent.com/6115534/42247645-5385ed70-7ee7-11e8-80bf-dc3a0daa01e7.png)

I think this screen is too large to be very useful.  I think each category should be a separate related display, and the program should generate a master screen with several related display menus.  Thoughts?

**Comment by thomascobb** [comment]
I'd second @bhill-slac on this, we generally use these screens only when commissioning the camera, to see what it does and poke parameters til it works. We then create a summary screen that we actually use in operation.
While we're commissioning, it's usually easier for me to see all the parameters on one large screen than lots of little ones with related displays, but that's down to personal preference

**Comment by MarkRivers** [comment]
I have taken a compromise approach.  The problem is that medm shrinks the screen to be the maximum width of the display.  That means that if it is very wide all the widgets shrink, and text that should fit no longer does.  So my Python adl converter specifies the maximum number of category columns per screen and then makes several screens, each with that many columns.  The last screen may have fewer of course.

Here are the first 2 screens (of a total of 4) for a Point Grey BlackflyS camera.

![image](https://user-images.githubusercontent.com/6115534/42325955-52a87200-802d-11e8-8b8a-ec3df8dad21d.png)

![image](https://user-images.githubusercontent.com/6115534/42326019-8ce0521c-802d-11e8-8dff-b70a775c6e99.png)

It needs a little work to tidy up the title and category labels, but I think it looks pretty good.  I plan to make a generic Aravis camera medm screen with related displays for 8 or 16 feature screens like this.  In addition to the standard P and R macros it will take a C macro that is used to construct the name of the camera-specific feature screens.

**Comment by prjemian** [comment]
The larger problem is with the designers of these screens.  

1. Too much info for one screen
2. Designer has a screen with more pixels than many users will have.

Try to keep the screens below 1k x 720 in size.

**Comment by MarkRivers** [comment]
It is a tradeoff between the size of each screen and the total number of screens.  These screens are being autogenerated by a Python script from the XML file read from the GeniCAM camera.  The Python script for adl files I have written generates screens with 4 columns that are 1445x870 maximum.  Most displays today are at least 1600x1024, so these will fit.  If I were to reduce them to 3 columns that would result in 
25% more screens. Not sure which is better?

**Comment by prjemian** [comment]
To be general, you should not assume screen sizes larger than 1000 columns.

**Comment by MarkRivers** [comment]
Where did you get the number 1000?

**Comment by MarkRivers** [comment]
The nice thing about using the Python script to create the adl files is that you can just change 2 numbers to control the size of the resulting screens.  If the screens are too large for your taste make them smaller, as shown here:

This is with these lines in makeAdl.py.  This results in 4 feature adl files:
maxScreenWidth = 1500
maxScreenHeight = 850
![image](https://user-images.githubusercontent.com/6115534/42379663-184c682c-80f1-11e8-9252-71feb8522fce.png)

This is with these lines.  This results in 8 feature adl files.
maxScreenWidth = 980
maxScreenHeight = 850
![image](https://user-images.githubusercontent.com/6115534/42380055-3ceb7d16-80f2-11e8-9f23-84ecb0a42ce7.png)

Note that the fonts and widget sizes are the same for the 2 screens, they just look larger in the second screen shot on Github.

**Comment by MarkRivers** [comment]
I have now created an aravisTop.adl screen.  This launches aravisCamera.adl with the normal P and R macros, but also with a new C macro which is the name of a specific camera model.  That is used to locate the Feature screens for that particular camera.

![image](https://user-images.githubusercontent.com/6115534/42380663-4b52f346-80f4-11e8-9d6a-c6da525f3c9a.png)

This is the new version of aravisCamera.adl.  It is very similar to ADBase.adl except for the related displays for the Features.  The related displays are:
* $(C)-features.adl  This is labeled custom and is not autogenerated by the Python script.  It is the file that can be manually customized to hold all of the important features for that camera.
* $(C)-features_N.adl, where N=1-8.  N could be increased to 15 if needed.

![image](https://user-images.githubusercontent.com/6115534/42380584-0de96580-80f4-11e8-83f2-193efdab3c37.png)

This is the 4'th Feature screen for this camera, loaded from aravisCamera.adl.

![image](https://user-images.githubusercontent.com/6115534/42380698-6a5a9e42-80f4-11e8-9ca0-c8db5b839b49.png)

**Comment by MarkRivers** [comment]
I am happy with this solution and am closing this issue.
