### ISSUE TITLE
aravisGigE does not limit  features and enum values to those actually available

### ISSUE THREAD

**Issue by MarkRivers** [areaDetector/aravisGigE#42]
aravisGigE presents all features and enum choices present in the XML file equally, whether or not they are actually available.  Whether a feature or enum value is available can change in response to the current state of the camera.

For example, for a Point Grey camera these are the choices that are presented for the ARVI_AdcBitDepth feature.
![aravis_choices](https://user-images.githubusercontent.com/6115534/43046434-76dc1726-8d8e-11e8-9a44-7d3447fd935f.png)

However, the only value which is actually available for this camera is Bit10. 

Failing to distinguish available from unavailable choices can be very confusing for the user.  The only way to detect the problem when selecting an unavailable option is to look for error messages at the iocsh prompt.

GenICAM and the underlying aravis software provide a mechanism to query whether a feature or enum is currently available.  The areaDetector drivers that are based on vendor SDKs (e.g. ADPointGrey, ADSpinnaker) currently do this as follows:
- In the OPI screen a feature that is not available is not shown. This is done by having a separate isAvailable record for each feature and making the visibility of the widget be based on the value of this record.
- The enum values for mbbo/mbbi records are created at run-time based on the choices actually available using the asynEnum interface.  If enum choices change at run-time callbacks are made to device support to update the list of allowed choices.

Because enum values can change dynamically at run-time, but EPICS channel access does not provide a callback mechanism for new enum choices, it is necessary to close and re-open screens when the enum choices have changed.

I propose to implement this for aravisGigE as well.  Initially I will just create static enums based on the availability when the camera first connects, but ultimately need to implement callbacks so that enum menus update dynamically at run-time.

**Comment by MarkRivers** [comment]
I have now enabled the asynEnum interface in the driver and implemented the aravisCamera::readEnum() method.  This method is called during iocInit() and returns only the available enum values at that time.

The following screen shot shows the enum values for PixelFormat __before__ the readEnum() method was added.  Note that it shows 16 values, which is the maximum that EPICS can show.  However, many of these values are not available, and some that are available may not be shown because the 16 limit was reached.

![image](https://user-images.githubusercontent.com/6115534/43049754-bf0c38b2-8dc2-11e8-8e74-d18d859f9d04.png)

This screen shot is __after__ the readEnum() method was added.  Note that now there are only 10 enum choices, and the RGB8Packed choice is now shown. Previously it was not shown because it was beyond the first 16 choices.

![image](https://user-images.githubusercontent.com/6115534/43049794-5776c5b8-8dc3-11e8-8ae5-1e77465e828c.png)

**Comment by MarkRivers** [comment]
I have now implemented run-time update of the enum choices.  This is done in the aravisCamera::getNextFeature() method.  For enum features it builds the list of available enum choices and calls doCallbacksEnum().  This allows menus to change dynamically at run-time based on other feature changes.

As an example,  the following shows the first features screen for a Point Grey Blackfly camera when ColorMode=RGB1.  Note that there are valid choices for SaturationAuto, BalanceWhiteValue, and BalanceRatioSelector.  

![image](https://user-images.githubusercontent.com/6115534/43050433-48125d2a-8dce-11e8-9328-80861d4a0dfb.png)

The following screen shot shows the first feature screen when ColorMode is changed to Mono.  Note that the enum choices for SaturationAuto, BalanceWhiteValue, and BalanceRatioSelector are now disabled (N.A. is only choice).  Before this enhancement to the aravisCamera driver the values available in RGB1 mode would have been shown here, but an error would have occurred if the user had tried to change any of them while in Mono mode.  Note that it was necessary to close this screen and re-open it for these changes to appear because of the limitations of EPICS Channel Access.

![image](https://user-images.githubusercontent.com/6115534/43050415-e762cae6-8dcd-11e8-962d-153105874e98.png)

**Comment by MarkRivers** [comment]
These changes have been pushed to the aravis-5 branch on Github.

**Comment by thomascobb** [comment]
This repo is deprecated in favour of https://github.com/areaDetector/ADAravis . Please raise an issue on that repo if this is still an issue.
