### ISSUE TITLE
Error compiling in ubuntu bionic

### ISSUE THREAD

**Issue by attokdz** [areaDetector/aravisGigE#44]
Hi to everyone!

I tried to compile aravisGigE in a ubuntu 18.04 and I got the following error:

```
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE            -D_X86_64_  -DUNIX  -Dlinux     -O3 -g   -Wall      -mtune=generic     -m64 -fPIC -I. -I../O.Common -I. -I. -I.. -I../../../include/compiler/gcc -I../../../include/os/Linux -I../../../include      -I/opt/epics/modules/synApps/support/asyn-R4-33/include     -I/opt/epics/modules/synApps/support/areaDetector-R3-3-1/ADSupport/include/os/Linux -I/opt/epics/modules/synApps/support/areaDetector-R3-3-1/ADSupport/include   -I/opt/epics/modules/synApps/support/areaDetector-R3-3-1/ADCore/include -I/opt/epics/base/include/compiler/gcc -I/opt/epics/base/include/os/Linux -I/opt/epics/base/include     -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I../../../vendor/aravis-linux-x86_64/include/aravis-0.6    -c ../aravisCamera.cpp
/usr/bin/ar -rc    libaravisCamera.a        aravisCamera.o 
/usr/bin/ranlib libaravisCamera.a
make[3]: *** No rule to make target '../../../lib/linux-x86_64/libglib-2.0.a', needed by 'libaravisCamera.so'.  Stop.
make[3]: Leaving directory '/opt/epics/modules/synApps/support/areaDetector-R3-3-1/aravisGigE/aravisGigEApp/src/O.linux-x86_64'
/opt/epics/base/configure/RULES_ARCHS:58: recipe for target 'install.linux-x86_64' failed
make[2]: *** [install.linux-x86_64] Error 2
make[2]: Leaving directory '/opt/epics/modules/synApps/support/areaDetector-R3-3-1/aravisGigE/aravisGigEApp/src'
/opt/epics/base/configure/RULES_DIRS:84: recipe for target 'src.install' failed
make[1]: *** [src.install] Error 2
make[1]: Leaving directory '/opt/epics/modules/synApps/support/areaDetector-R3-3-1/aravisGigE/aravisGigEApp'
/opt/epics/base/configure/RULES_DIRS:84: recipe for target 'aravisGigEApp.install' failed
make: *** [aravisGigEApp.install] Error 2
```

I add in the CONFIG_SITE.local the following entry (otherwise doesn't find glib-objects.h)

```
WITH_GLIB = YES
GLIB_EXTERNAL = YES
GLIB_INCLUDE =/usr/include/glib-2.0 /usr/lib/x86_64-linux-gnu/glib-2.0/include
GLIB_LIB=glib-2.0
```

Any idea how to solve it?

Thanks!

**Comment by MarkRivers** [comment]
Did you install the glib2-devel package?  I recently wrote instructions on how to build aravis on Centos7, including installing the required packages.

https://areadetector.github.io/master/ADGenICam/ADGenICam.html#installing-aravis

The instructions for Ubuntu will be similar, but using `apt install` rather than `yum install`.

If you want to try it, there is now a new ADAravis driver that is intended to replace aravisGigE.  It uses the new ADGenICam driver as well.

**Comment by attokdz** [comment]
Thanks for the quick reply!

Yes, glib2.0-dev is install (in ubuntu is libglib2.0-dev). I also try with ADAravis and got exact same problem:

`make[4]: *** No rule to make target '../../../lib/linux-x86_64/libglib-2.0.a', needed by 'libADAravis.so'.  Stop.`

But I promise ;) that I have the package install indeed I have the file /usr/lib/x86_64-linu-gnu/libglib-2.0.a  but is looking for it in other location!

**Comment by jwlodek** [comment]
In the `CONFIG_SITE.local.linux-x86_64` file there is a `glib-2.0_DIR` definition, perhaps this is not set? I believe I had to add
```
glib-2.0_DIR = /usr/lib/x86_64-linux-gnu
```
when building ADAravis on ubuntu.

**Comment by attokdz** [comment]
Thank a lot for your replies!

Now both (ADAravis and aravisGigE) compiles nicely!
