### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by MarkRivers** [areaDetector/aravisGigE#7]
I have followed the instructions in the top-level README.md.

I ran install.sh.

I typed "make" and got the following errors:

corvette:~/devel/areaDetector/aravisGigE>make
make -C ./configure install 
make[1]: Entering directory `/home/epics/devel/areaDetector-2-4/aravisGigE/configure'
make -C O.linux-x86_64 -f ../Makefile TOP=../.. \
    T_A=linux-x86_64 install
make[2]: Entering directory `/home/epics/devel/areaDetector-2-4/aravisGigE/configure/O.linux-x86_64'
perl /corvette/usr/local/epics/base-3.14.12.5/bin/linux-x86_64/convertRelease.pl checkRelease
make[2]: Leaving directory `/home/epics/devel/areaDetector-2-4/aravisGigE/configure/O.linux-x86_64'
make[1]: Leaving directory `/home/epics/devel/areaDetector-2-4/aravisGigE/configure'
make -C ./vendor install 
make[1]: Entering directory `/home/epics/devel/areaDetector-2-4/aravisGigE/vendor'
make -C O.linux-x86_64 -f ../Makefile TOP=../.. \
    T_A=linux-x86_64 install
make[2]: Entering directory `/home/epics/devel/areaDetector-2-4/aravisGigE/vendor/O.linux-x86_64'
make[2]: *** No rule to make target `../aravis-linux-x86_64/lib/libaravis-0.4.a', needed by `../../lib/linux-x86_64/libaravis-0.4.a'.  Stop.
make[2]: Leaving directory `/home/epics/devel/areaDetector-2-4/aravisGigE/vendor/O.linux-x86_64'
make[1]: *** [install.linux-x86_64] Error 2
make[1]: Leaving directory `/home/epics/devel/areaDetector-2-4/aravisGigE/vendor'
make: *** [vendor.install] Error 2
corvette:~/devel/areaDetector/aravisGigE>

It is looking for libaravis-0.4.a.  When I look on the aravis Web site http://ftp.acc.umu.se/pub/GNOME/sources/aravis/
the most recent release seems to be 0.3.5? 
The install.sh script also defines VERSION as 0.3.5, not 0.4.a.

Can someone please update README.md to have build instructions that work with the current release of Aravis and areaDetector 2-4?

**Comment by thomascobb** [comment]
fixed in 46c30f4cc22829f366dd8aa7a253d1ea3883abe3
